# Generated by Django 5.0.1 on 2024-02-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0003_fileversion_content_hash_fileversion_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileversion",
            name="content_hash",
            field=models.CharField(max_length=64),
        ),
    ]
