# Generated by Django 5.0.1 on 2024-02-13 21:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0004_alter_fileversion_content_hash"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="fileversion",
            unique_together={("file_name", "content_hash", "user")},
        ),
    ]
